name: Convert JS to SGModule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Conversion Script
        run: python .github/scripts/convert-js-to-sgmodule.py
        env:
          USERNAME: czy13724
          REPO: TEST

  deploy:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Upload Surge Modules
        uses: actions/upload-artifact@v2
        with:
          name: sgmodule
          path: ${{ github.workspace }}/sgmodule/*

      - name: Push to TEST Repository
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Convert js file"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
