name: Convert JS to SGModule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Conversion Script
        run: python .github/scripts/convert-js-to-sgmodule.py
        env:
          USERNAME: czy13724
          REPO: TEST

      - name: Save Surge Modules to artifacts
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts/sgmodule
          cp -r javascript/* $GITHUB_WORKSPACE/artifacts/sgmodule
        if: always()

  deploy:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Upload Surge Modules
        uses: actions/upload-artifact@v2
        with:
          name: sgmodule
          path: artifacts/sgmodule

      - name: Checkout TEST Repository
        uses: actions/checkout@v2
        with:
          repository: czy13724/TEST
          path: TEST
          ref: main

      - name: Move Surge Modules to TEST Repository
        run: |
          mkdir -p TEST/sgmodule
          cp -r $GITHUB_WORKSPACE/TEST/artifacts/sgmodule/* TEST/sgmodule
        if: always()

      - name: Commit and Push Changes to TEST Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add TEST/sgmodule
          git commit -m "Update Surge Modules"
          git push
        if: always()
