name: Convert JS to SGModule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Conversion Script
        run: python .github/scripts/convert-js-to-sgmodule.py
        env:
          USERNAME: czy13724
          REPO: TEST

  deploy:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Download Surge Modules
        uses: actions/download-artifact@v2
        with:
          name: sgmodule
          path: ${{ github.workspace }}/sgmodule
        # 注释：从 artifacts 下载 sgmodule 文件夹

      - name: Copy Surge Modules to sgmodule
        run: |
          mkdir -p $GITHUB_WORKSPACE/sgmodule
          cp -r $GITHUB_WORKSPACE/sgmodule/* $GITHUB_WORKSPACE/sgmodule
        # 注释：将下载的 sgmodule 文件夹复制到仓库根目录下的 sgmodule 文件夹中

      - name: Deploy Surge Modules
        uses: actions/upload-artifact@v2
        with:
          name: sgmodule
          path: sgmodule
        # 注释：将 sgmodule 文件夹上传为工作流的 artifacts
