name: Convert JS to SGModule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Conversion Script
        run: python .github/scripts/convert-js-to-sgmodule.py
        env:
          USERNAME: czy13724
          REPO: TEST

      - name: Save Surge Modules
        uses: actions/upload-artifact@v2
        with:
          name: sgmodule
          path: sgmodule
        if: always()

  deploy:
    needs: convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git config user.name "${{ secrets.GITHUB_ACTOR }}"

      - name: Extract Surge Modules
        uses: actions/download-artifact@v2
        with:
          name: sgmodule
          path: sgmodule

      - name: Copy Surge Modules to TEST/sgmodule
        run: |
          mkdir -p TEST/sgmodule
          cp -r sgmodule/. TEST/sgmodule
        if: always()

      - name: Commit and Push Changes
        run: |
          cd TEST
          git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git config user.name "${{ secrets.GITHUB_ACTOR }}"
          git add sgmodule
          git commit -m "Update Surge Modules"
          git push origin main


