name: Image Workflow

on:
  push:
    paths:
      - 'test/*.png'
  workflow_dispatch:

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate JSON
      run: |
        python .github/scripts/generate_json.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: json-artifact
        path: ${{ github.workspace }}/.github/scripts/generated_json.json

    - name: Push to TEST repository
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const path = '.github/scripts/generated_json.json';
          const content = fs.readFileSync(path, 'utf8');
          const base64Content = Buffer.from(content).toString('base64');
          const response = await octokit.repos.createOrUpdateFile({
            owner: 'czy13724',
            repo: 'TEST',
            path: 'generated_json.json',
            message: 'Add generated JSON file',
            content: base64Content,
            branch: 'main',
          });
          console.log(response);
